### ISSUE TITLE
pinafore notification settings lost?

### ISSUE THREAD

**Issue by pwFoo** [nolanlawson/pinafore#1364]
I experienced some time that notification settings are lost (disiabled instead of enabled). Tested 3-4 times until it seems to be saved.
Verified with activate and reload with some delay. Checkboxes unchecked again.
First time it was enabled and checked one day later because i got no notifications.

**Comment by pwFoo** [comment]
Version 1.11.2

**Comment by nolanlawson** [comment]
Which browser and OS is this?

**Comment by pwFoo** [comment]
OnePlus 5
- Chrome for Android
- Android 9 (OxýgenOS 9.0.7)

**Comment by pwFoo** [comment]
Updated pinafore to latest / 1.11.6.

**Comment by pwFoo** [comment]
I'm sure to enabled all notification settings. Today I get mastodon notifications in android about mentioned and nothing from pinafore.

![image](https://user-images.githubusercontent.com/333408/62656764-372c5b00-b965-11e9-8aff-5be53352fe92.png)

 Checkt the settings and disabled again?

![image](https://user-images.githubusercontent.com/333408/62656818-55925680-b965-11e9-8074-6e9c876f8394.png)

I'm really sure to enabled notifications, checked it, reloaded the app, closed the app and opened to check again *g*
So it really looks like a bug?

**Comment by pwFoo** [comment]
Today I updated to 1.11.7 without problems. Next notification I got via mastodon client I noticed that all notifications are disabled after update. 

I enabled alle notifications 4 or 5 times (with time delay, reload app, checkboxes unchecked some times), until I get an error message, that another subscription exists. Not all notifications are enabled, but all notifications missed (got by mastodon client at the same device to verify that).

![image](https://user-images.githubusercontent.com/333408/62724781-0820f280-ba14-11e9-9fbe-22a79a2f189c.png)

New that time! Also inside of the pinafore app I got NO notifications?

![image](https://user-images.githubusercontent.com/333408/62724826-21c23a00-ba14-11e9-8dde-e7fd53f72be5.png)

And notification settings looks good...

![image](https://user-images.githubusercontent.com/333408/62724856-356da080-ba14-11e9-934a-77e3e7fce967.png)


To be sure it isn't a browser / cache / system-worker problem I'll clear all data to verify next time.
But in the past that hasn't solved the problem.

**Comment by pwFoo** [comment]
Verified on mobile. I don't need to enable push notifications more than one time! Looks like it's pending in background and checkboxes are unchecked!

Maybe you need a pending / waiting indicator during the request isn't finished?
Now waiting for the next notification to check it.

**Comment by amyspark** [comment]
I get this a lot with Pleroma, it seems to delete push subscriptions for some reason. The endpoint `api/v1/push/subscription` returns 404 and Pinafore does not update the subscription accordingly.

**Comment by pwFoo** [comment]
Short time ago I changed mobile. Haven't experienced that problem with the new mobile or the old one before the change. Maybe fixed with one of the updates?

**Comment by achou11** [comment]
I'm still experiencing this issue on my mobile device. Attempting to enable the push notifications in the app don't seem to be persisted reliably, and even when they are, the notifications don't actually work. I also made sure that notification permissions were enabled at the browser level for the pinafore domain.

Pixel 6
Firefox Nightly app
Pinafore 2.5.1

I figure it's an issue with Pinafore itself because I enabled them in https://elk.zone/ (a different PWA client for Mastodon), and the notifications work properly there.

Happy to create a separate issue if there's anything here that deserves its own attention, but figured that this issue is similar enough.
